# Generated by Django 3.2.3 on 2021-06-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
            ],
        ),
    ]
