# Generated by Django 3.2.3 on 2021-06-29 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio'),
        ),
    ]
